module.exports = {
    preloadjs:{
        expand:true,
        cwd:'../../js/PreloadJS/lib/',
        src:'preloadjs-0.4.1.combined.js',
        dest:'src/js/libs/'
    },
    ratchet_css:{
        expand:true,
        cwd:'../../ui/ratchet/dist/css/',
        src:'*.css',
        dest:'src/css/'
    },
    ratchet_fonts:{
        expand:true,
        cwd:'../../ui/ratchet/dist/fonts/',
        src:'ratchicons.*',
        dest:'src/fonts/',
    },
    dist_ratchet_fonts:{
        expand:true,
        cwd:'../../ui/ratchet/dist/fonts/',
        src:'ratchicons.*',
        dest:'dist/fonts/'
    },
    //https://github.com/lepture/yue.css
    yue_css:{
        expand:true,
        cwd:'../../ui/yue.css/',
        src:'yue.css',
        dest:'src/css/'
    }
};
